# Base configs
baseurl: "https://123tommyd.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Thanasi Dimos"
subtitle: "See the world through my eyes!"
author: "Thanasis Dimos"
header:
 title: "Photography"
 subtitle: "by Thanasis Dimos"
footer:
 name: "Hey there, my name is Thanasis"
 bio: "I am an Air Traffic control Engineer. Photography is my hobby"
 github: "A website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AD"
social_urls:
  facebook: "https://www.facebook.com/someone"
  twitter: "https://www.twitter.com/someone"
  instagram: "https://www.instagram.com/someone"
  dribbble: "https://dribbble.com/someone"
  linkedin: "https://in.linkedin.com/in/someone"
  github: "https://www.github.com/someone"
